name: Deploy Workflow new



jobs:
  manual_approval:
      runs-on: ubuntu-latest
      steps:

        - name: checkout code
          run: git clone https://github.com/DenzMoses/ghactions.git 
          
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-cov
    
        - name: Run Final Steps
          run: |
            pytest --cov= ./ghactions/python/ --cov-fail-under=60


